spring:
  datasource:
    url: jdbc:postgresql://10.13.31.13:5432/microservices
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  rabbitmq:
    host: 10.13.31.13
    port: 5672
server:
  port: 8084
service-s:
  wsEndpoint: http://localhost:8084/ws
app:
  storage:
    minio:
      endpoint: http://10.13.31.13:9003/
      admin: admin
      password: adminpassword
      bucket: student-files
      presign-ttl-seconds: 900  # 15 minutes
